### ISSUE TITLE
How do I install this thing?

### ISSUE THREAD

**Issue by master0v** [POM57/HeliTrim#2]
I copied the files into ./X-Plane 12/Resources/plugins/HeliTrim yet it doesn't show in the list of plugins in side the xplane.

**Comment by POM57** [comment]
> I copied the files into ./X-Plane 12/Resources/plugins/HeliTrim yet it doesn't show in the list of plugins in side the xplane.

This is just the source code without the necessary SASL stuff. If you just want to use the plugin download it in it's complete form from x-plane.to or the org forum.

**Comment by master0v** [comment]
Yep, that's the one I am using, and it doesn't work:

<img width="1398" alt="Screenshot 2024-02-15 at 17 33 23" src="https://github.com/POM57/HeliTrim/assets/18746987/194ba92b-9a59-4835-bd14-ec0190473a71">

<img width="591" alt="Screenshot 2024-02-15 at 17 34 28" src="https://github.com/POM57/HeliTrim/assets/18746987/5f51d5b7-f3d7-4fcb-a337-87dd3a3f9f6b">

**Comment by POM57** [comment]
Are you on apple silicon? HeliTrim doesn't support that yet, you can download the latest SASL and paste the custom modules, config and main.lua from HeliTim into it for now.

**Comment by master0v** [comment]
Yes, Apple silicon.  SASL doesn't show up in the list of plugins (Plugin Admin) either :(

**Comment by POM57** [comment]
I updated the SASL so you can now re-download it from x-plane.to or org and it should hopefully work natively on Apple silicon.

**Comment by master0v** [comment]
Thank you, the plugin now loads!  Appreciate you looking into it and fixing so quickly!
